# Documentation
# * mdbook   https://rust-lang.github.io/mdBook/
# * template https://github.com/kg4zow/mdbook-template/

[book]
authors             = ["Avery"]
language            = "en"
multilingual        = false
src                 = "src"
title               = "Haskell Roguelike Tutorial with Roguefunctor and Bearlibterminal"

[output.html]
additional-css      = [ "section-lines.css" , "version-commit.css" ]
curly-quotes        = false
git-repository-url  = "https://github.com/ppkfs/roguelike-tutorial"
no-section-label    = true

[preprocessor.version-commit]
renderers           = [ "html" ]
command             = "./version-commit"
